spring.application.name=AdminApi
server.port=8081

#BD
spring.datasource.url=jdbc:postgresql://localhost:5433/AdminBD
spring.datasource.username=admin
spring.datasource.password=signIn
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true


#Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9094,localhost:9095,localhost:9096

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.spring.json.trusted.packages=*

# Consumer Configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.listener.ack-mode=manual

#Topic
app.kafka.topic.alerted-transactions=alert-topic
app.kafka.topic.input-transactions=input-transactions
app.kafka.topic.input-transactions-dlq=input-transactions-dlq

#Transaction Limits
app.transaction.max-concurrent=10000

# Inside-config logging
logging.level.com.example.AdminApi.config=WARN

# Spring Security Debug Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.example.AdminApi.services.CustomUserDetailsService=DEBUG

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.idempotency-key-ttl=1800

# Actuator & Prometheus Configuration
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# ML Model Configuration
ml.model.path=classpath:ml/fraud_model_production_15f.onnx
ml.model.version=production-15f
ml.model.default-threshold=0.5

# Feature calculation windows
ml.features.deviation-window-days=30
ml.features.velocity-window-minutes=10
