spring.application.name=AdminApi
server.port=8081

#BD
spring.datasource.url=jdbc:postgresql://localhost:5433/AdminBD
spring.datasource.username=admin
spring.datasource.password=signIn
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9094,localhost:9095,localhost:9096

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.spring.json.trusted.packages=*

#Topic
app.kafka.topic.input-transactions=input-transactions
app.kafka.topic.input-transactions-dlq=input-transactions-dlq

#Transaction Limits
app.transaction.max-concurrent=10000

# Inside-config logging
logging.level.com.example.AdminApi.config=WARN

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.idempotency-key-ttl=1800
