spring.application.name=AdminApi

#BD
spring.datasource.url=jdbc:postgresql://localhost:5433/AdminBD
spring.datasource.username=admin
spring.datasource.password=signIn
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Migration
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml